services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=budget_tracker
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - budget-network

  mongodb:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
      - MONGO_INITDB_DATABASE=budget_tracker
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"
    networks:
      - budget-network

  auth-service:
    build:
      context: .
      dockerfile: auth_service/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=your-secure-secret-key-here
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - MASTER_USERNAME=admin
      - MASTER_PASSWORD=secret
    depends_on:
      - postgres
    networks:
      - budget-network

  budget-service:
    build:
      context: .
      dockerfile: budget_service/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8000
      - MONGODB_URL=mongodb://mongo:mongo@mongodb:27017/budget_tracker?authSource=admin
    depends_on:
      - auth-service
      - mongodb
    networks:
      - budget-network

networks:
  budget-network:
    driver: bridge