version: '3.8'

services:
  auth-service:
    build:
      context: .
      dockerfile: auth_service/docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=your-secure-secret-key-here 
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - MASTER_USERNAME=admin
      - MASTER_PASSWORD=secret
    volumes:
      - ./:/app
    networks:
      - budget-network

  budget-service:
    build:
      context: .
      dockerfile: budget_service/docker/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8000
    depends_on:
      - auth-service
    networks:
      - budget-network

networks:
  budget-network:
    driver: bridge